### ISSUE TITLE
Fallback in resmod if iteration model fails

### ISSUE THREAD

**Issue by stellabelin** [pharmpy/pharmpy#1097]
Currently, it can throw the following error: 

```
dofv = base_ofv - model.modelfit_results.ofv
AttributeError: 'NoneType' object has no attribute 'ofv'
```

**Comment by ZheHuang96** [comment]
Hi, I think it looks similar to #845. We should check the input of resmod. The necessary things that I can remember are:

1. input model fit results: ofv and residuals because we need CWRES for the tool.
2. $TABLE must include ID and TIME column, which are needed in the tool to set up its own data frame.

Maybe there are other general things we need to check before resmod run?

**Comment by stellabelin** [comment]
Hi! Sorry, I did not write the issue very clearly, this error happened to one of the iteration models, a longer part of the error (full stack in the above mentioned issue):
``` 
File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/resmod/tool.py", line 176, in post_process
res = calculate_results(models)
File "/miniconda/envs/r-reticulate/lib/python3.8/site-packages/pharmpy/tools/resmod/results.py", line 52, in calculate_results
dofv = base_ofv - model.modelfit_results.ofv
AttributeError: 'NoneType' object has no attribute 'ofv'
```
In this case, dofv should be NaN I guess. I still think it makes sense to check 1&2 that you mentioned before starting though!
