### ISSUE TITLE
Cannot create a Json file for the following bootstrap

### ISSUE THREAD

**Issue by cossonvalerie** [pharmpy/pharmpy#137]
I cannot create a Json file for a bootstrap, res = create_results("bootstrap_dir2")  

I get the following error message

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  KeyError: 'Row -1000000000 not available in ext-file' 

The compressed bootstrap_dir2 folder is provided in the Box

**Comment by rikardn** [comment]
Thanks for reporting this and providing the files. I can confirm that it is a bug. It was caused due to Pharmpy not being able to read in parameter estimates and ofvs for terminated runs. I have fixed so that this can now run. What is still missing is filtering of failed runs. This is tracked here: https://github.com/pharmpy/pharmpy/issues/89
