### ISSUE TITLE
problem with retrieve_final_model code

### ISSUE THREAD

**Issue by rosemarychen99** [pharmpy/pharmpy#1484]
### Bug report

I tried to retrieve final model of amd result object. and get the following error message
![image](https://user-images.githubusercontent.com/35337934/212309621-77cbcd24-97ee-44fe-8223-3e0d41c2c403.png)
When I tried to retrieve final model of a model search result object, there is another error message:
![image](https://user-images.githubusercontent.com/35337934/212309868-5a41eb20-c095-4fb9-bba7-4a09c5b3ef0c.png)

**Comment by stellabelin** [comment]
Hi! The first issue is that AMD doesn't currently work the same way as the other subtools, and the selected final models have not been moved up. A current workaround would be to use the results file for the final subtool in AMD. The second issue occurs since it is the input model to the tool. A workaround for this would be to read in the model in the `modelfit`-subdirectory. Both of these will be fixed by making the AMD into a proper tool (with the same tool database structure as the subtools etc) and handle hierarchical databases (see #1502). Please reopen if these workarounds did not work!
