### ISSUE TITLE
Redesign index of modelfit_results.predictions

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#1552]
This index is currently ID and TIME, but there are models that does not have TIME. To be able to always have the same index we could switch to a plain range. This could be problematic for some other cases so some thinking is needed before switching.

**Comment by duvnjakzrinka** [comment]
Hi @rikardn,

I'm using pharmpy and pharmr version 0.107. I see that meanwhile, you switched to keeping only PRED and CIPREDI, without TIME and ID (same for modelfit_results.residuals with keeping only CWRES). 

I'm trying to establish a modelling workflow using pharmpy that includes the creation of GoF plots after model fitting.  
Without these indices, I can not use modelfit_results.predictions and modelfit_results.residuals for making my own ggplots.

At the moment, my workaround is to readin NONMEM output table and then create the plots I need. I was wondering if there is some smarter way to do this.

I also just wanted to draw your attention to pharmpy plotting functions, since they are also not working for the same reason. For example, after running this code:
"plot_dv_vs_pred(model = model, predictions = model_res$predictions)"
I'm getting the following error:
"Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  ValueError: cannot join with no overlapping index names"

PS: In the documentation, the examples are still displaying ID and TIME indices.

Thank you!

Zrinka

**Comment by rikardn** [comment]
I don't think we have made that switch yet, but we are thinking about doing it. The reasons being:

1. Some datasets doesn't have TIME and in that case this table will have a different index depending on the dataset
2. Some datasets have multiple records at the same time point, which makes the index non-unique, which can cause issues when doing operations on it.

Instead having an index with the number of the original data record will make still make it possible to join the predictions dataframe with the dataset to be able to get ID and TIME in the same table.

Since we haven't done this change yet, I think what you experience is an issue with R not being able to properly round trip the multiindex. @stellabelin Can multiindexed dataframes be roundtripped like this currently?

**Comment by rikardn** [comment]
This has now been changed so that the index for `predictions` is a simple integer range index.
