### ISSUE TITLE
Estmethod – solvers

### ISSUE THREAD

**Issue by leiwolfm** [pharmpy/pharmpy#1738]
I’m currently exploring the estmethod tool in PharmR, and I manage to obtain the results file when I test different estimation methods, but when I try to test estmethod with different solvers it doesn't work; I have one of the following error messages :

« ValueError : Invalid input ‘model’ : testing non-linear solvers on linear system is not supported » or 
« AttributeError: 'NoneType' object has no attribute 'statements’. » 

However, I checked that the model has been correctly recognised with the command model$statements.

Could you please advise?
Thank you very much for your time and assistance.

**Comment by rikardn** [comment]
Thanks for reporting this. What does your `$SUBROUTINES` and `$ESTIMATION` look like for the input model?

**Comment by leiwolfm** [comment]
I've tested different models, for example 
$SUBROUTINES ADVAN13 TOL9 with
$ESTIMATION METHOD=1 INTERACTION MAXEVAL=9999 PRINT=5 FORMAT=,1PE13.6 
and
$SUBROUTINES ADVAN6 TOL5 with 
$ESTIMATION METHOD=COND INTER MAXEVAL=99999 SADDLE_RESET=1.

Thank you very much!

**Comment by rikardn** [comment]
This should be fine. Could you provide a full reproducible example?

**Comment by rikardn** [comment]
Thanks for the examples. I have the dataset so I will be able to test.

**Comment by rikardn** [comment]
Sorry I missed that you were having problems with different solvers not methods. I will retest

**Comment by rikardn** [comment]
Here are my results:

For the first model there were some issues that I now have fixed. This model will run in next version.

For the second model Pharmpy refuses to run it because the ODE system is linear so there is really no need to test solvers for non-linear systems. Is there a reason why you would like to test numerical solvers instead of the general linear solver here?

`estmethod` still adds an IMP evaluation step even though it is not really needed when only testing solvers. I opened an other issue for this: https://github.com/pharmpy/pharmpy/issues/1754

Thanks for reporting these problems.
