### ISSUE TITLE
Cannot create Json file for psn frem results

### ISSUE THREAD

**Issue by cossonvalerie** [pharmpy/pharmpy#178]
Although the results I get from psn frem may not be that relevant nor making sense, since I get some results from psn, I believe that nevertheless I should be able to create a json file from it. However I get the following error message 

```res = create_results("frem_dir1")```

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Uncertainty covariance matrix not positive-definite 
```

the zipped file of the psn frem directory provided in the drop box

**Comment by rikardn** [comment]
Thanks for reporting this. The covariance matrix generated by NONMEM is not positive semi-definite so the error is the correct one. You can force it to become positive definite by doing:

```R
res = create_results("frem_dir1", force_posdef_covmatrix=TRUE)
```

However in this case the covariance matrix must be changed quite a bit to become positive definite. It seems as if the parameter sampling takes quite some time after this. I let it run for 45 minutes before stopping it. There is also the option of forcing all samples drawn from the covmatrix to be posdef, which might speed things up. `force_posdef_samples=TRUE` or use the "bipp"-method instead with `method="bipp"`. Using the bipp method I can get results.

There was a related bug in the check for positive semi-definiteness that I have fixed with: 

e0f7b1cf446a6d0c5cc9afcd5f4b14134c624225
