### ISSUE TITLE
Implement new ModelDatabase

### ISSUE THREAD

**Issue by rikardn** [pharmpy/pharmpy#1922]
The new model database will be flat. The primary key will be model objects. The filesystem implementation will be in a .models directory with subdirectories named after the hashes. Contents of the directories will be the same as today. The datasets will also be hashed and the hashes will be used instead of names in the .datasets directory. The database will also have a parents dict so that the full model tree can be recreated. Also the filename_extension could land as an attribute here if needed. For the lookups to be fast enough the hashing of the model needs to be cached. (Should the hash of the model also include the dataset? Perhaps the dataset hash could be cached by the model since it cannot be cached in the dataset itself. Cache invalidation warning for this, best handled in constructors and replace.)

Also the serialized model should be read when retrieving from the datbase.

Methods:

```
db.store_modelfit_results(model, modelfit_results)
modelfit_results = db.retrieve_modelfit_results(model)
parent = db.retrieve_parent_model(model)
```

**Comment by stellabelin** [comment]
Instead of having models as keys, an implementation key should be used (e.g. for a local database, this would be a path). Each run directory will have the implementation key to its parent to start with, instead of a parent dict. Methods to implement:

- [ ] `get_key(model) -> key`: a key will to start with be a string, for type hinting `Key = str` can be used (to avoid having to rewrite type hints if a proper `Key` class is added)
- [ ] `store_model_entry(self, model_entry) -> key`: the implementation key to the parent will also be stored with this method (i.e. in order for a model to be a parent it needs to have been run, raise if not in database)
- [ ] `retrieve_model_entry(self, model | key) -> model_entry`: raise if model doesn't exist
- [ ] `retrieve_model(key) -> model`: raise if model doesn't exist
- [ ] `rehash(self, context)`: copy files to new context with new hashes (since hashes can change between versions if there has been changes to the model object)
- [ ] `remove_model(model | key)`: mainly useful when a user has scripted workflows, remove as parent for all affected models
- [ ] `store_local_file(self, model, path)`
- [ ] `retrieve_local_files(self, model, path)`: as a first step retrieve all files, later an option for e.g. patterns could be implemented
- [ ] `store_metadata(self, model | key, metadata)`
- [ ] `retrieve_metadata(self, model | key) -> metadata`

**Comment by rikardn** [comment]
This has now been implemented and pushed except for the `rehash`. We'll need to see in the future when the need for this arises.
