### ISSUE TITLE
allow negative values in DV

### ISSUE THREAD

**Issue by sardnar** [pharmpy/pharmpy#2424]
### Feature request

I have another issue. I am trying log transform my DV . My concentration is low and some values are negative. Despite that just fitting base model works, but modelsearch raise: 

```
ValueError: Lower bound 0.0 cannot be greater than init -0.0138629436111989
```

**Comment by sardnar** [comment]
Hi @stellabelin. 
The base model gives "termination due to rounding" some online resources suggests increase sigdig to 6. However, I am not sure how to do that with pharmpy as the model was created from there.

**Comment by rikardn** [comment]
Thanks for the update. It seems that the `set_peripheral_compartment` cannot properly set the initial value. We should be able to fix it given this information.

**Comment by rikardn** [comment]
7ccfef5a55a5bce83d9cf0e75ad5be539ea73bd4f should fix so that `modelsearch` does not crash for cases where the DV or TIME has some negative values. Since the Pharmpy tools currently doesn't really support log-transformed DV the initial estimates created would be worse than if the data was on the normal scale. So currently I would recommend using non-transformed DV.

The reason that we opted to not support log transformed DV was because of the findings presented here:
https://www.page-meeting.org/default.asp?abstract=10128
