### ISSUE TITLE
question : Can a dataset be updated after creating a model with pharmpy/pharmr functions ? 

### ISSUE THREAD

**Issue by artikandms** [pharmpy/pharmpy#2984]
Hi ! 
I just have a question (not a issue this time ^^). 
I used the function `create_basic_pk_model` with my dataset corresponding to a single-compartment model with first order absorption. 
I then used 
`set_mixed_mm_fo_elimination(model)`
`seq_zo_fo_absorption(model)`
Then when I `fit(model)` obviously the dataset does not match. Is there a function or other to directly update the dataset according to our model, as does modelsearch? 
I don't know if I'm being clear.
Thank you :)

**Comment by antoniaih** [comment]
Hi,
Do I understand it correctly that you want to modify the dataset so that it matches the model better? This is not possible in pharmpy and it is not done in modelsearch either. In modelsearch the model is modified to match the data not the other way around.
There are however functions to modify the dataset in pharmpy such as adding a TAD column and some model modifications require the dataset to be modified as well but there is no function that changes the data to fit the model.

**Comment by artikandms** [comment]
Okay, thank you :)
