### ISSUE TITLE
Disabling Python warnings

### ISSUE THREAD

**Issue by king-of-poppk** [pharmpy/pharmpy#3264]
Is is possible to configure `pharmr` to silence the following warnings?

```console
~/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/model/external/nonmem/parsing.py:205: UserWarning: The parameter name CRCL is duplicated. Falling back to using THETA_6 instead.
  warnings.warn(
~/.virtualenvs/r-reticulate/lib/python3.10/site-packages/pharmpy/model/external/nonmem/parsing.py:97: UserWarning: The parameter name IIV is duplicated. Falling back to using OMEGA_2_2 instead.
  warnings.warn(
 ```

**Comment by rikardn** [comment]
Fixed with cddc855441fb8b90efd1c7348ce4157d69494ce9

**Comment by king-of-poppk** [comment]
Thanks for taking care of this!

**Comment by king-of-poppk** [comment]
Is there a way to disable this differently? For instance by configuring the name inference logic differently from the default? Perhaps something that only outputs NONMEM names?

**Comment by rikardn** [comment]
We used to have multiple options, but it created a big round-trip problem when something was read and written with different settings so we opted for being opinionated in how the names are parsed. One possibility instead is to have functions to rename parameters. For example a function could rename all parameters to THETA1,... OMEGA_1_1 etc.

**Comment by king-of-poppk** [comment]
Yep. I think it would be great if the initial names were NONMEM ones with no possible overlap. And have the names inference implemented as a separate function. I don't think it would be a problem then if that function warns or errors if it cannot find unique names.

**Comment by rikardn** [comment]
Actually I was thinking of the other way around. Default is to find names and then a separate function can rename to original NONMEM names. This way that function doesn't need to depend on the NONMEM AST.

**Comment by king-of-poppk** [comment]
I see this completely differently: naming parameters in comments is up to convention and should be defined separately from parsing. To me there is no "category mistake" with having an additional set of functions that are dependent on NONMEM details. It should actually turn out simpler to have the choice between

```py
model = parse(...)
# AND 
model = parse(...)
model = nonmem_set_parameter_names_from_comments(model)
```

rather than
```py
model = parse(...)
# AND 
model = parse(...)
model = nonmem_remove_parameter_names_from_comments(model)  # Or can you actually implement this generically?
```

. Or am I missing something?

**Comment by rikardn** [comment]
The original reason it is done like it is now is because of history with how PsN does it. But ofcourse we don't have to take that into consideration now.

When Pharmpy modifies a model by adding a parameter how should that be named? Currently we give it a name that has a meaning for example `POP_MDT` if transit compartments were added. We would like to be able to write the new model and read it in again and get the same parameter names. Wouldn't we loose round-tripability with your suggestion? This is the reason we also add `$ABBR` for added etas. (Now NONMEM 7.5 has an option in `$THETA` that could be used for naming thetas and we could use $ABBR also for omegas and sigmas.)

So not depending on the AST was not my main concern, but rather the loss of round-tripable parsing of the NONMEM parameter names.
