### ISSUE TITLE
add_estimation_step: idx argument is not taken into account

### ISSUE THREAD

**Issue by emiliesg** [pharmpy/pharmpy#394]
idx argument does not seem to be taken into account
For example: 

model <- load_example_model("pheno")
opts <- list('NITER'=1000, 'ISAMPLE'=100)
add_estimation_step(model, "IMP", tool_options=opts, **idx = 1**)
ests <- model$estimation_steps
ests

outputs the following: 
[[1]]
EstimationMethod("FOCE", interaction=True, cov=True, evaluation=False, maximum_evaluations=None, laplace=False, tool_options=None)

[[2]]
EstimationMethod("IMP", interaction=False, cov=False, evaluation=False, maximum_evaluations=None, laplace=False, tool_options={'NITER': 1000.0, 'ISAMPLE': 100.0})

**Comment by stellabelin** [comment]
Hi! `idx` needs to be before options, since the function takes keyword arguments as input. In Usage, it's: 
```
add_estimation_step(model, method, idx = NULL, ...)
```
Meaning `idx` in this case will be part of the `...` argument. However, it should give an error when you try to pass an argument that isn't valid. Also, I think in this case you want to use the 0 offset (meaning array indices start at 0, unlike R that starts at 1), if you want the new estimation step to be first. In `set_estimation_step` this is written but not in `add_estimation_method`, I'll add it to the documentation. For now, if you do the following it should work:
```
 add_estimation_step(model, "IMP", idx = 0, tool_options=opts)
```

**Comment by stellabelin** [comment]
Sorry, I wrote wrong: idx will be taken into consideration, it is just in this case `idx=1` will be the last position in the list of estimation steps, where you have it as an argument doesn't matter.
