### ISSUE TITLE
RMarkdown with Pharmpy

### ISSUE THREAD

**Issue by SCarter79** [pharmpy/pharmpy#71]
When writing models in RMarkdown (RStudio 1.1.456, R 4.0.0, pharmpy 0.11.0), the full model is printed for each change, even when not requested. i've attached the RMarkdown output here.

However, if the steps are all written within pipe, this does not happen e.g.

```
model21 = pharmpy$Model(here::here('Moxinidine/run2.mod')) %>%
  # change residual error model
  modeling$proportional_error() %>%
  modeling$update_source() %>%
  # Write to a new model
  modeling$write_model(here::here('Moxinidine/run21.mod'))
```

[Moxinidine_rpt_pytest_241120.zip](https://github.com/pharmpy/pharmpy/files/5723737/Moxinidine_rpt_pytest_241120.zip)

**Comment by rikardn** [comment]
This is same as in python and expected if you run interactively unless assigning to a variable. Or does it print also when assigning? The following should not print anything:

```
model21 <- read_model('run2.mod')
```

**Comment by SCarter79** [comment]
It shouldn’t print anything, but it does in R, in prints out the whole NONMEM model.

**Comment by rikardn** [comment]
Because you are not assigning the results of the function it is expected to print it out. Compare

```
model <- read_model('run2.mod')
```

and

```
read_model('run2.mod')
```

The first doesn't print and the second does. So I fail to see the issue here. You could use the `invisible` function in R but that gets a bit ugly. Assign to a variable, pipe or do more things in the same chunk since it is only the final statement that will have its output printed in one rmarkdown chunk.

**Comment by SCarter79** [comment]
Ah perfect thankyou. So it was more a bug in my knowledge.

**Comment by rikardn** [comment]
No problem. Closing.
