### ISSUE TITLE
What is the impact of "model<-" as well as "update_source()" ?

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmpy#77]
Dear Rikard,

As discussed during the meeting,
Could you explain me what is the purpose of "model<-" and "update_source()".
In fact, the results seems to be the same with or without these command lines.

Kind regards,
Simon

**Comment by rikardn** [comment]
Hi! A NONMEM model object basically contain two things. The abstract syntax tree (AST) from the parsing of the model file and the Pharmpy representation of the model. When doing changes/transformations to the model only the Pharmpy representation gets changed and the update of the AST takes place when `update_source` is called. In other words the model is perfectly valid and usable in Pharmpy after a transformation, but in order to create the new NONMEM code, `update_source` needs to be called.

A model object is only copied when the copy method is explicitly called (`model$copy()` in R) otherwise a reference to the same model is passed around. This is a bit different from what is common in R and is similar to the reference classes in R. Since the model object contains quite a bit it is quite a bit faster this way.

I keep this issue up as a reminder to put this in the documentation somewhere.
