### ISSUE TITLE
Adding IIV on a parameter

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmpy#86]
Hi,

When adding an ETA to a parameter e.g. IIV on a the MAT e.g.
![image](https://user-images.githubusercontent.com/75624013/105175651-88fa7e00-5b24-11eb-9941-23fa83b978a9.png)

ETA parameter in the NONMEM code and in the model$random_variables will have a different names:
ETA_MAT instead of ETA(3)
![image](https://user-images.githubusercontent.com/75624013/105175952-e0005300-5b24-11eb-8e55-21eccc81daa3.png)

Versus in the nonmem code
![image](https://user-images.githubusercontent.com/75624013/105178681-a7627880-5b28-11eb-9e04-d7e11391cab1.png)

Adding a correlation bewteen ETA2 and ET3 is then leading to an error 
![image](https://user-images.githubusercontent.com/75624013/105178804-cd881880-5b28-11eb-91fa-f37e9af4a980.png)

Kind regards,
Simon

**Comment by rikardn** [comment]
In the Pharmpy internal representation of the model it is allowed to use any name for parameters or random variables. In fact the transformation code doesn't even know that it is working with a NONMEM model. This is to allow support for other tools or model formats in the future. The `add_etas` names the added etas `ETA_` and the parameter name and the omega `IIV_` and the parameter name.

When reading a NONMEM model Pharmpy can for the parameter names use the label comments, but for the etas we currently have no way of reading in alterative names, so all will be named ETAs when reading a model.

When creating the NONMEM source code via `update_source()` all random variables that doesn't have valid NONMEM names will be given one (`ETA(n)`) in the code but will retain the Pharmpy name in the Pharmpy model.

So if you want to add a correlation you would use 'ETA(2)' and 'ETA_MAT' as the names of the random variables.

This is something we should add to the documentation.

**Comment by SimonBuatois** [comment]
Hi Rikard, 

For simplicity sake, I think that it would be best to always use eta number.
In fact, I found it counter-intuitive to adapt the following command line "create_rv_block(c('ETA(2)', 'ETA_MAT'))"  depending on the fact that the parameter was coming from NONMEM or  "added" via pharmpy.
In addition, what would happen if the Same eta is being used for multiple parameters?

Best,
Simon

**Comment by rikardn** [comment]
I'll try to brainstorm a bit to see what would be possible.

1. We don't want the `add_etas` function to have to know of the underlying model format.
2. ETAs in nonmem can be named ETA(XX) through the $ABBR, which is something we would like to support.
3. NONMEM 7.5 support naming of THETAs through $THETA, which we would like to support in the future
4. We want a variable to have only one name in Pharmpy, hence the configuration to either use classical names for parameters or the label comment for NONMEM models.
5. We want to allow any name for variables and not be constrained to what NONMEM allows.
6. Since ETAs in NONMEM are numbered we would need to renumber them for example when ETA(1) and ETA(3) are put in a block without ETA(2). This would change the names of the ETAs for all future models which would add confusion.

I think number 6 should tell us that it is better to use non-numbered symbols so that the name could be kept through-out an analysis.

## Option 1: Put the given name of the random variable in the NONMEM code for the next read of the model

One problem is indeed that we cannot "remember" the names of the random variables. One option would be to use `$ABBR REPLACE ETA(MAT)=ETA(3)` when generating the NONMEM code. This could be "name mangled" into `ETA_MAT` in Pharmpy. Another option that we have used before is to set `ETA_MAT = ETA(3)` in the abbreviated code. A third is to have some kind of metadata comments.

## Option 2: Let `update_source()` change the names of all random variables to the NONMEM names. 

This risks making things even more confusing, since you would need to run `update_source()` to get the renaming

## Option 3: Use different "find name" methods depending on type of variable that can be overridden by the `nonmem.Model` class.

This would give `ETA(3)` in your example, but will give different names to variables depending on underlying model language or tool.

I think we should go with option 1 so that names of ETAs can be set freely and the name could be kept in the model file.

**Comment by rikardn** [comment]
## Option 4: Allow a name option to `add_etas`

`add_etas(model, 'MAT', 'exp', name='ETA(3)')`

Perhaps we should do both opts 1 and 4

**Comment by SimonBuatois** [comment]
I agree, we should probably go with both option 1 and 4.
It might also be interesting to think about the connection between T1 and T2. 
Should we adapt T1 depending on the method we choose for T2?

**Comment by rikardn** [comment]
Ok, we'll do that!

Good point. I'll check if this or other variable naming issues would impact assemblerr.

**Comment by stellabelin** [comment]
Configuration is now possible to parse and write $ABBR (5b171074403170eef84aafce81f6a06734c19ce1 and feceb126d0aa5b7e376d8d831d97439f01652360) and documentation is written, custom names for e.g. add_iiv is now supported
