### ISSUE TITLE
Clarify datainfo is needed for AMD dataset

### ISSUE THREAD

**Issue by joaoabr** [pharmpy/pharmpy#949]
Pharmpy/PharmR 0.73.1

These lines of code
```
dataset_path <- "../dataset/dataset_filtered.csv"
order <- c('structural', 'iivsearch', 'iovsearch', 'residual', 'allometry', 'covariates')
run_amd(input=dataset_path,
        modeltype='pk_iv',
        order=order,
        categorical=c('RACE'),
        continuous=c('AGE'),
        allometric_variable='BW',
        occasion='CENT')

```
Lead to:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  FileNotFoundError: [Errno 2] No such file or directory: 'file.csv'

Detailed traceback:
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\tools\run_amd.py", line 101, in run_amd
    model = convert_model(model, 'nonmem')  # FIXME: Workaround for results retrieval system
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\modeling\common.py", line 238, in convert_model
    new = nonmem.convert_model(model)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\plugins\nonmem\model.py", line 80, in convert_model
    nm_model.statements = model.statements
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\plugins\nonmem\model.py", line 535, in statements
    self.statements  # Read in old statements
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\plugins\nonmem\model.py", line 487, in statements
    comp = compartmental_model(self, sub.advan, sub.trans, des)
  File "C:\PROGRA~1\Python39\lib\site-packages\pharmpy\plugins\nonmem\advan.py", line 17, in compartment
```
Do you recognize this error?

**Comment by stellabelin** [comment]
Should also be a more sensible error

**Comment by pharmpy-dev-123** [comment]
The error is raised because that version of Pharmpy did not handle model-less datasets with a `RATE` column. This issue was duplicated in #989. Related is #328. Will be fixed in next release via #1015.

@joaoabr Do you have a `RATE` column in that dataset? Do you expect Pharmpy to interpret this `RATE` column the same way NONMEM would?

> Thank you for commenting this, I agree that it should be much clearer that both are needed in the documentation, will create a "warning/note"-section to make it clearer.

If the documentation has been updated regarding the need for `.datainfo` file then we can close here.

**Comment by stellabelin** [comment]
The documentation is updated (like this: https://pharmpy.github.io/latest/amd.html#input), not as a warning/not though since a default can be used, should it be made more clear? But I was also thinking we might still want a more clear error, maybe a input validation before starting to run the tool (in the case of a missing datainfo file it will create a default, but maybe it should warn that it does so?)

**Comment by stellabelin** [comment]
Closing this issue since documentation has been updated, we also have issue #1032 for input validation.
