### ISSUE TITLE
Trying to add IOV via R

### ISSUE THREAD

**Issue by SimonBuatois** [pharmpy/pharmpy#96]
Hi,

I'm trying to add IOV via R but I don't really understand how to do it.

I tried :
model <- model %>%
  add_iov("DOSE",c('ETA(1)')) %>%
  update_source()

model <- model %>%
  add_iov("DOSE",c('ETA(1)')) %>%
  update_source()

model <- model %>%
  add_iov("DOSE",'CL') %>%
  update_source()

But I keep getting the same error message:
![image](https://user-images.githubusercontent.com/75624013/106262933-fe9cd300-6223-11eb-8072-0f564899c280.png)

I guess that I am not doing it the right way but it is difficult via the doc to do the translation from python to R.

Best,
Simon

**Comment by SCarter79** [comment]
in pipe do you need an = first i.e. `model = model %>%` - this may not solve the issue, just how i thought it worked?

**Comment by stellabelin** [comment]
I can reproduce the error. This is similar to #91, ETA(1) is being broken into a list (['E', 'T', 'A', '(', '1', ')']) and therefore it tries to find 'E' as a symbol (which doesn't exist). If you use list() instead of c() it should work as a temporary solution, but I will implement so that you can have just 'ETA(1)' as an input.
