### ISSUE TITLE
Skip IOVsearch by default in run_amd when there is only one occasion

### ISSUE THREAD

**Issue by pharmpy-dev-123** [pharmpy/pharmpy#984]
@liuxl17 reported this

**Comment by ZheHuang96** [comment]
Hi Aurelien@pharmpy-dev-123, I think the issue that Xuanlin @liuxl17 reported is: She wants to skip the iovsearch, but if she uses the default order and didn't specify the occasion argument, the run will stop rather than skip iovsearch and continue the progress. I think I might offer the wrong information to them or didn't explain it clear previously. The idea of `run_amd` is, if you want to skip some subtools or want to define your own run order of subtool, you need to specify the order argument. 

The only unique thing about iovsearch is users have to specify the occasion column to let iovsearch run, there is no 'default' occasion column because pharmpy can not get the occasion information from datainfo. So in a word, the iovsearch in amd can only be activated when `order=[..., 'iovsearch'], occasion='VISI'`.

I think one of the things we can improve here is 

1. Give a warning when users have iovsearch in `order` but forget to specify the` occasion` column. 
2. According to Xuanlin's test, the whole run will stop. I think there are two options here: either we stop the run or we skip this subtool and continue the next subtool, I am not sure which option is much better? (I can see both advantages and disadvantages of these two options...)

I think user should pre-check the dataset to make sure there are at least two different categories of occasions before they wants to run the iovsearch, but I might be wrong...

**Comment by liuxl17** [comment]
> 

Yes, that's what I mean. The IOVsearch is unnecessary when there is only one occasion in the case (means there's no OCC column in the dataset). 
For now, the only way to skip it is to specify this by removing ```'iovsearch'``` in the ```order=[...]``` argument, and it works well. What I am concerned about is if you expect this AMD tool to be smart enough to skip the iovsearch subtool automatically when it finds there's no column related to occasion in the dataset. Otherwise, you just need to specify this as a tip in the user guide.

**Comment by pharmpy-dev-123** [comment]
#1065 implements both methods.
